config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'

  get 'pages/about_us',      to: 'pages#about_us', as: 'about_us'
  
  get 'pages/contact_us',   to: 'pages#contact_us', as: 'contact_us'
  
  get 'pages/elementary',   to: 'pages#elementary', as: 'elementary'
  
  get 'pages/old_elementary', to: 'pages#old_elementary', as: 'old_elementary'
  
  get 'pages/old_highschool', to: 'pages#old_highschool', as: 'old_highschool'
  
  get 'pages/eye_to_eye', to: 'pages#eye_to_eye', as: 'eye_to_eye'
  
  get 'pages/spreading_kindness', to: 'pages#spreading_kindness', as: 'spreading_kindness'
  
  get 'pages/worth_it', to: 'pages#worth_it', as: 'worth_it'
  
  get 'pages/its_my_life', to: 'pages#its_my_life', as: 'its_my_life'
  
  get 'pages/go_viral', to: 'pages#go_viral', as: 'go_viral'
  
  get 'pages/setup'

  get 'pages/scheduling',   to: 'pages#scheduling', as: 'scheduling'

  get 'pages/highschool',   to: 'pages#highschool', as: 'highschool'

  get 'pages/downloads'
  
  get 'pages/count_on_me', to: 'pages#count_on_me', as: 'count_on_me'
  
  get 'pages/the_right_choice', to: 'pages#the_right_choice', as: 'the_right_choice'
  
  get 'pages/point_of_view', to: 'pages#point_of_view', as: 'point_of_view'
  
  get 'pages/be_a_hero', to: 'pages#be_a_hero', as: 'be_a_hero'
  
  get 'pages/be_amazing', to: 'pages#be_amazing', as: 'be_amazing'
  
  get 'pages/golden_rule', to: 'pages#golden_rule', as: 'golden_rule'
  
  get 'pages/quest_for_respect', to: 'pages#quest_for_respect', as: 'quest_for_respect'
 
  get 'pages/event_prep', to: 'pages#event_prep', as: 'event_prep'
  
  get 'pages/jobs', to: 'pages#jobs', as: 'jobs'
  
  get 'pages/jobsrequirements', to: 'pages#jobsrequirements', as: 'jobsrequirements'
  
  get 'pages/jobsdescription', to: 'pages#jobsdescription', as: 'jobsdescription'
  
  get 'pages/jobsthetour', to: 'pages#jobsthetour', as: 'jobsthetour'
  
  get 'pages/jobsfaq', to: 'pages#jobsfaq', as: 'jobsfaq'
  
  get 'pages/share_story', to: 'pages#share_story', as: 'share_story'
  
  get 'pages/jobscontact', to: 'pages#jobscontact', as: 'jobscontact'
  
  get 'pages/jobs_application', to: 'pages#jobs_application', as: 'jobs_application'
  
   root 'pages#home'
   

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def hello
    render html: "Hello, World!"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about_us
  end

  def contact_us
  end
  
  def elementary
  end
  
  def old_elementary
  end
  
  def the_right_choice
  end
  
  def count_on_me
  end
  
  def its_my_life
  end
  
  def go_viral
  end
  
  def point_of_view
  end
  
  def eye_to_eye
  end
  
  def spreading_kindness
  end
  
  def worth_it
  end
  
  def be_a_hero
  end
  
  def golden_rule
  end
  
  def quest_for_respect
  end
  
  def be_amazing
  end
  
  def scheduling
  end

  def highschool
  end

  def downloads
  end
  
  def event_prep
  end
  
  def jobs
  end
  
  def jobsrequirements
  end
  
  def jobsdescription
  end
  
  def jobsfaq
  end
  
  def share_story
  end
  
  def jobscontact
  end
  
  def jobs_application
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Camfel Productions</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <!-- Meta tags -->
  <meta charset="utf-8">
  <meta name="description" content="Camfel Productions has been making student development and bully prevention programs for 40 years. Our three-screen school assembly programs are designed to reach your students with valuable character lessons in a contemporary and attention grabbing format.">
  <meta name="keywords" content="bullying prevention, anti-bullying programs, character development, anti bullying programs, school assembly, bullying assembly, school assembly ideas, school assemblies"> <!-- add more keywords -->
  <meta name="author" content="Camfel Productions">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>

<!-- Begin Body -->
<body>
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", root_path, :class=> "soft-link" %></li>
          <li class="soft-link"><%= link_to "About Us", about_us_path, :class=> "soft-link" %></li>
          <li><%= link_to "Elementary School Programs", elementary_path, :class=> "soft-link" %></li>
          <li><%= link_to "Middle & High School Programs", highschool_path, :class=> "soft-link" %></li>
          <li><%= link_to "Scheduling/Get Info", contact_us_path, :class=> "soft-link" %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </nav>
<br />
<br />



<%= yield %>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>

<br />

<footer>
    <div class="footer" id="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3> Camfel </h3>
                    <ul>
                        <li> <%= link_to "Home", root_path%> </li>
                        <li> <%= link_to "About Us", about_us_path%> </li>
                        <li> <%= link_to "Event Prep/FAQ", event_prep_path %> </li>
                        <li> <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                            <input type="hidden" name="cmd" value="_s-xclick" />
                            <input type="hidden" name="hosted_button_id" value="72FNCWQ8ZAMPC" />
                            <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
                            <img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1" />
                            </form>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3> Presentations </h3>
                    <ul>
                        <li> <%= link_to "Elementary Programs", elementary_path%> </li>
                        <li> <%= link_to "Middle School Programs", highschool_path%> </li>
                        <li> <%= link_to "High School Programs", highschool_path%> </li>
                    </ul>
                </div>
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3> Contact </h3>
                    <ul>
                        <li> <%= link_to "Contact Us", contact_us_path%> </li>
                        <li> <a href="tel:1-800-522-6335"> <strong class = "callmemaybe">Toll Free: <br />1-800-522-6335</strong> </a> </li>
                    </ul>
                </div>
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3> Resources </h3>
                    <ul>
                        <li> <a href="http://characteredtools.com/" target = "_blank"> Classroom Programs </a> </li>
                        <li> <a href="http://characteredtools.com/character" target = "_blank"> Videos </a> </li>
                        <li> <a href="http://characteredtools.com/bannersbookmarksbuttons.html" target = "_blank"> Banners & Bookmarks </a> </li>
                        <li> <a href="http://characteredtools.com/posters.html" target = "_blank">  Posters </a> </li>
                    </ul>
                </div>
                <div class="col-lg-3  col-md-4 col-sm-4 col-xs-6">
                    <h3> Follow Us </h3>
                    <ul>
                        <li>
                            <li> <%= link_to "Tell Us Your Story", share_story_path%> </li>    
                        </li>
                    </ul>
                    <ul class="social">
                        <li> <a href="https://www.facebook.com/CamfelAssembly/" target = "_blank"> <i class=" fa fa-facebook" >   </i> </a> </li>
                        <li> <a href="https://twitter.com/camfelusa?lang=en" target = "_blank"> <i class="fa fa-twitter">   </i> </a> </li>
                        <li> <a href="https://vimeo.com/user5305460" target = "_blank"> <i class="fa fa-vimeo-square">   </i> </a> </li>
                        <li> <a href="https://www.instagram.com/camfelproductions/" target = "_blank"> <i class="fa fa-instagram">   </i> </a> </li>
                        <li> <a href="https://www.youtube.com/user/camfelproductions" target = "_blank"> <i class="fa fa-youtube">   </i> </a> </li>
                    </ul>
                </div>
            </div>
            <!--/.row--> 
        </div>
        <!--/.container--> 
    </div>
    <!--/.footer-->
    
    <div class="footer-bottom">
        <div class="container">
            <p class="pull-left"> Copyright © Camfel 2017. All right reserved. </p>
            <div class="pull-right">
                <ul class="nav nav-pills payments">
                	<!--<li><i class="fa fa-cc-visa"></i></li>-->
                 <!--   <li><i class="fa fa-cc-mastercard"></i></li>-->
                 <!--   <li><i class="fa fa-cc-amex"></i></li>-->
                 <!--   <li><i class="fa fa-cc-paypal"></i></li>-->
                </ul> 
            </div>
        </div>
    </div>
    <!--/.footer-bottom--> 
</footer>

</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/downloads.html.erb
<h1>Pages#downloads</h1>
<p>Find me in app/views/pages/downloads.html.erb</p>
this is a change for the sake of change

app/views/pages/elementary.html.erb
<div id="title" class="container padding-top-bottom">
    <h1 id="elementaryschool">Elementary School Assemblies</h1>
    <h4 id="production-explanation">
        Powerful and interactive 3-screen assembly programs designed to erase the insecurities
        and fears students face daily, replacing them with an understanding of their true 
        potential and the desire and motivation to be the best they can be in whatever 
        circumstances they face.
    </h4>
</div>
<div id="banner-image-2">
    <div class = "banner-text text-center invisible">
    
        <p class = "banner-title">Elementary School Assembly</p>
        <p> 
            Bully Prevention and character building presentations that will engage and
            <br />
            motivate your students to exceed in school and in life
        </p>
        <ul>
            <li>Interactive, Relatable, & Fun</li>
            <li>Two Versions of Each Program K-2 & 3-5</li>
        </ul>
    </div>
</div>
<div class="container-fluid">
    <br />
    <div class="row">
        <div class="col-md-1">
            <div>
                <br />
                <br />
                <br />
                <br />
                <%= link_to 'Option #1', spreading_kindness_path, :class=>"btn btn-primary"%>
            </div>
        </div>
        <div class = "col-md-3">
            <p class="md-size-text"><strong>SPREAD KINDNESS</strong></p>
            <%= link_to spreading_kindness_path :class=>"soft-link" do %>
            <span>
                <%= image_tag("spread kindness logo.jpg", :class=>"img-responsive") %>
            </span>
            <% end %>
        </div>
        <div class="col-md-7" id="presentation-summary">
            <p class="md-size-text"><strong>Theme: Social Manners and Citizenship</strong></p>
            <p class="md-size-text">
                <strong>SPREAD KINDNESS</strong> is a high energy three-screen multimedia presentation. It will challenged
                students to make being kind a priority for their lives. your students will discover that one small act of
                kindness, an encouraging word or a smile can change someone's attitude for the entire day. They'll
                find that bullying and being critical are not the best way to make friends or to be the kind of person
                they wish to be. Spreading Kindness involves helping, sharing, listening, and teaching. If we do those things we can 
                change both how we are perceived and how we see ourselves. By working together to SPREAD KINDNESS we can
                improve our lives and inspire those around us to excel and achieve success. 
            </p>
            <%= link_to 'Contact Us', contact_us_path, :class=>"btn btn-primary pull-right left-padding btn-margin-top"%> 
            <%= link_to 'Learn More', spreading_kindness_path, :class=>"btn btn-primary pull-right btn-margin-top"%> 
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-1">
            <br />
            <br />
            <br />
            <br />
            <%= link_to 'Option #2', count_on_me_path, :class=>"btn btn-primary"%>
        </div>
        <div class="col-md-3">
            <p class="md-size-text"><strong>Count on Me!</strong></p>
            <%= link_to count_on_me_path :class=>"soft-link" do %>
            <span>
                <%= image_tag("countonme_logo.png", :class=>"img-responsive") %>
            </span>
            <% end %>
        </div>
        <div class="col-md-7" id="presentation-summary" class="hidingBox">
            <p class="md-size-text"><strong>Theme: Responsibility & Honesty</strong></p>
            <p class="md-size-text">
                <strong>COUNT ON ME!</strong> is an engaging three-screen school assembly. The program will
                motivate your students to make responsible choices. Students will be challenged to stop 
                making excuses or blaming others for their mistakes. They will be encouraged to take 
                responsibility for their actions, consider others and keep their promises. COUNT ON ME is 
                an incredibly powerful motivational school assembly challenging your students to make positive
                choices, help prevent bullying, and be respectful of others. 
            </p>
            <%= link_to 'Contact Us', contact_us_path, :class=>"btn btn-primary pull-right left-padding btn-margin-top"%>  
            <%= link_to 'Learn More', count_on_me_path, :class=>"btn btn-primary pull-right btn-margin-top"%> 
        </div>
    </div>
</div>

app/views/pages/jobsrequirements.html.erb
<div class = "container">
    <div id = "banner-image-jobs" class = "margin-top">
        
    </div>
    
    <nav class="navbar navbar-custom " role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Jobs Home", jobs_path, :class=> "soft-link" %></li>
          <li><%= link_to "Basic requirements", jobsrequirements_path, :class=> "soft-link" %></li>
          <li><%= link_to "Basic Description", jobsdescription_path, :class=> "soft-link" %></li>
          <li><%= link_to "About Camfel", about_us_path, :class=> "soft-link", target: :_blank %></li>
          <li><%= link_to "The Tour", jobsthetour_path, :class=> "soft-link" %></li>
          <li><%= link_to "Faq", jobsfaq_path, :class=> "soft-link" %></li>
          <li><%= link_to "Apply", jobs_application_path, :class=> "soft-link", target: :_blank %></li>
          <li><%= link_to "Contact", jobscontact_path, :class=> "soft-link" %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </nav>
    <div class = "row">
        <div class = "col-md-9">
            <h4>Flexibility</h4>
            <p>We need people who are easily adaptable and flexible and love the challenge of new situations, 
            climates, cultures and connecting with new types of people. You will have tough days and great days on the road;
            however, we promise that the rewards and benefits far outweigh the challenges you might face. 
            You'll walk away from your tour having accomplished something great, having a greater understanding of the world in which you live, 
            and having learned something about yourself along the way.</p>
            <h4>Love people</h4>
            <p>You will spend just as much time dealing with people in this job as you will dealing with technology. 
            From principals and pastors to students and hotel staff - we expect the highest of standards with whomever you encounter. 
            We expect our presenters to always be courteous, professional, and understanding while maintaining a high level of customer service at all times.</br></br>

            You will also be staying in a communal living space during training, as well as on the road with one other person. 
            You will need to have respect for others while being independent and punctual, maintaining a high level of integrity in all situations.</p>
            <h4>Leadership Characteristics</h4>
            <p>We are looking for servant leaders. We are looking for people who are willing to lead and serve. 
            Being a leader means that you are a person of integrity, positivity, vision and commitment. 
            The moment you step into a venue for a show, you are in the spotlight. 
            Students and staff alike are watching you to see if what you say and represent matches up with who you are as a person. 
            We place a high value on strong character values and expect our presenters to be the type of leaders that students will desire to follow, 
            as you will be communicating with people one-on-one as well as in large group contexts. 
            Serving and loving people is crucial to the success of a Camfel presenter and as a leader altogether. 
            Leadership is not a title or even a role; it is becoming a person of character, integrity and influence.</p>
            <h4>Work and play</h4>
            <p>Your daily routine will involve running the show at a school in the morning,
            driving to a second school, and then driving to the next day's location.</br></br>

            While this job does not require you to be a top athlete, there is a bit of physical activity involved. 
            You will be lifting and moving equipment that may weigh up to 50 pounds.</br></br>
            
            Some of your days are going to be long. You may get worn out from time to time. 
            Although we will not expect you to work 20 hours a day, there will be days where you will have multiple shows in multiple venues and have a drive as well.</br></br>

            We need people who know how to have fun, work hard and play herd. 
            You'll have many days to explore and we encourage our presenters to discover new foods and cultures, sight-see,
            go skiing, go kayaking, go hiking, catch a ball game, etc. The country will literally be your playground.</p>
            <h4>Be committed to the vision</h4>
            <p>We want you to believe in this company and our mission of impacting students. 
            We want you sold on our vision before you step on the plane or get in a car to make your way out here. 
            We want our presenters to fulfill their committed time and do so with a positive attitude, while possessing a servant's heart. 
            We encourage our presenters to get to know the company, ask questions and become a part of the Camfel experience.</p>
        </div>
        <div class = "col-md-3">
            <%= image_tag("jobimages/student_help.jpg", :class=> "padding-bottom" )  %>
            <%= image_tag("jobimages/KidsBullySign.jpg", :class=> "padding-bottom" )  %>
            <%= image_tag("jobimages/KidsWithJennHannah.jpg" )  %>
        </div>
    </div>
    <div class = "row blackbackground margin-top">
        <div class= "col-md-4">
            <%= link_to jobsfaq_path :class=> "soft-links"  do %>
                <span >

                  <%= image_tag("jobimages/faq(icon.png")  %>

                </span>
            <% end %>
        </div>
        <div class= "col-md-4">
            
            <%= link_to jobsthetour_path :class=> "soft-links"  do %>
                <span >
                  <%= image_tag("jobimages/tour(icon.png")  %>
                </span>
            <% end %>
        </div>
        <div class= "col-md-4">
            
            <%= link_to jobs_application_path :class=>"soft-link", target: :_blank do %>
                <span>
                   <%= image_tag("jobimages/apply(icon.png") %>
                </span>
            <% end %>   
        </div>
    </div> 
    <div class = "row">
       <div class = "col-md-3">
            <p>"I can say that without a doubt Camfel has helped me to develop my public speaking skills, character, 
            work ethic, and faith. My teammate and other coworkers were some of the greatest friends that I have had 
            in a long time, that now feel like family. We came together from diferent places and stages in life, and 
            were united because of our common mission/goal. Only someting that God can do." 
            </br></br> [+]Brian Alexander 18/19 Tour</p>
        </div>
        <div class = "col-md-3">
            <p>"The beaches of the west coast, the Texan vastness, wildlife of all sorts, the Goonie's house, 
            General Lee, Napoleon Dynamite's school, and Chuck Norris are just a few of the unforgettable things 
            that we have seen since we have hit the road with Camfel! One of the best things is that you get 
            the unique opportunity to speak into the lives of so many people. So impact lives, see & do unforgettable things, 
            travel the country and get paid to do it! We will never regret the time we spent with Camfel!"</br></br> [+]Josh & Brittany Sievers, 2012/2013</p>
        </div>
        <div class = "col-md-3">
            <p>My experience working with Camfel has been wonderful and I highly recommend anyone to work for them. 
            It is a great company to work for all around. You get to see so much of America and grow personally, and spiritually. 
            If you have a heart for youth, and want to make a difference then working for them is something to consider.  
            </br></br> [+]Adriel Kroneberger 16/17 Tour</p>
        </div>
        <div class = "col-md-3">
            <p>"Working with Camfel has by far been one of the best, stretching and challenging experiences I have had in my life. 
            God taought me so many important life lessons, grew me in ways I never thought possible, and deepened my relationship with Him. 
            Everyday we had the opportunity to speak life into students who needed to hear the message, God's message. 
            As His vessel He allowed me to vistit 39 states and reach over 59,000 students. Camfel provides you the unique opportunity to 
            share the love of Christ with youth, see new places, meet new people and grow spiritually. If you allow it, it'll be the best, 
            challenging, but most rewarding job you might ever have in your life."
            </br></br> [+]Tara McDannel, 2018/2019</p>
        </div>
    </div>
</div>    
    

app/views/pages/jobsthetour.html.erb
<div class = "container">
    <div id = "banner-image-jobs" class = "margin-top">
        
    </div>
    
    <nav class="navbar navbar-custom " role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Jobs Home", jobs_path, :class=> "soft-link" %></li>
          <li><%= link_to "Basic requirements", jobsrequirements_path, :class=> "soft-link" %></li>
          <li><%= link_to "Basic Description", jobsdescription_path, :class=> "soft-link" %></li>
          <li><%= link_to "About Camfel", about_us_path, :class=> "soft-link", target: :_blank %></li>
          <li><%= link_to "The Tour", jobsthetour_path, :class=> "soft-link" %></li>
          <li><%= link_to "Faq", jobsfaq_path, :class=> "soft-link" %></li>
          <li><%= link_to "Apply", jobs_application_path, :class=> "soft-link", target: :_blank %></li>
          <li><%= link_to "Contact", jobscontact_path, :class=> "soft-link" %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </nav>
    
    <div class = "row">
        <div class = "col-md-6">
            <%= image_tag("jobimages/tourphoto_group.jpg" )  %>
            
            <p class = "text-center">So you're thinkin of joining the Camfel team, but you're not sure what life will be like once you get here?</p>
            <p>If you speak with any of our past presenters they will all tell you pretty much the same things - life on the road is a blast.</br></br>

            Sure there are going to be ups and downs; you'll get tired and worn out, but what makes it all worth it is seeing students lives 
            impacted with a message of change and hope.</br></br>

            From the wood-covered mountains of Washington to the urban landscape of Harlem in New York and everywhere in between. You'll 
            be sure to see and experience a ton while you're on the road. Between shows our techs go skiing, 
            explore the sights and sounds of cities such as Boston, New York, San Fransisco, Chicago and many others, and relax in some pretty nice hotel rooms.</br></br>

            If you have any questions about life on the road, please call: <a href="tel:1-626-960-6922 x 103"></a> Or feel free to email us at jobs@camfel.com. </p>
            
            
            <div class = "row margin-top">
                <div class = "col-md-2"></div>
                <div class = "col">
                    <%= image_tag("jobimages/HanKarWhiEmm.jpg" )  %>
                </div>
            </div>
        </div>
        <div class = "col-md-6">
            <%= image_tag("jobimages/brett_ny.jpg", :class=> "padding-bottom")  %>
            
            <div class="insetborder embed-responsive embed-responsive-16by9">
                  <iframe class="embed-responsive-item" src="https://player.vimeo.com/video/320780737" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
                </div>
            

        </div>
    </div>
    <div class = "row blackbackground margin-top">
        <div class= "col-md-4">
            <%= link_to jobsfaq_path :class=> "soft-links"  do %>
                <span >

                  <%= image_tag("jobimages/faq(icon.png")  %>

                </span>
            <% end %>
        </div>
        <div class= "col-md-4">
            
            <%= link_to jobsthetour_path :class=> "soft-links"  do %>
                <span >
                  <%= image_tag("jobimages/tour(icon.png")  %>
                </span>
            <% end %>
        </div>
        <div class= "col-md-4">
            
            <%= link_to jobs_application_path :class=>"soft-link", target: :_blank do %>
                <span>
                   <%= image_tag("jobimages/apply(icon.png") %>
                </span>
            <% end %> 
        </div>
    </div>
</div>

app/views/pages/old_elementary.html.erb
<div id="banner-image-2">
	<!-- empty div -->
</div>
<div class="container">
	<div id="title">
		<h1 id="elementaryschool">Old Elementary School Assemblies</h1>
		<h4 id="production-explanation">
			Powerful and interactive 3-screen assembly programs designed to erase the insecurities and fears students face daily, 
			replacing them with an understanding of their true protential and the desire and motivation to be ther best they can 
			be in whatever circumstances they face.
		</h4>
	</div>
	<br />
	<!-- Columns are always 50% wide, on mobile and desktop -->
	<div class="row">
		<div class="col-md-6">
			<%= link_to be_a_hero_path :class=>"soft-link" do %>
			 <span>
				 <%= image_tag("beaheroemail.png", :class=>"img-responsive") %>
			 </span>
			<% end %>
		</div>
		<div class="col-md-6" id="presentation-summary" class="hidingBox">
			<p><strong>Theme: Being Your Best</strong></p>
			<p>
				<strong>BE A HERO!</strong> is an interactive program that will encourage your students to excel in school, 
				to help stop bullying, and to be a role-model - a "hero" for others to follow.
			</p>
			<%= link_to 'Contact Us', contact_us_path, :class=>"btn btn-primary pull-right left-padding"%>  
			<%= link_to 'Learn More', be_a_hero_path, :class=>"btn btn-primary pull-right"%> 
		</div>
	</div>
	<br />
	<div class="row">
		<div class="col-md-6">
			<%= link_to golden_rule_path :class=>"soft-link" do %>
			 <span>
				 <%= image_tag("the_golden_rule_logo.jpg", :class=>"img-responsive") %>
			 </span>
			<% end %>
		</div>
		<div class="col-md-6" id="presentation-summary">
			<p ><strong>Theme: Respect</strong></p>
			<p >
				<strong>THE GOLDEN RULE</strong> will demonstrate that true respect is earned over time. 
				When we do our best in class and when we build up others instead of being mean, we will gain "true" respect.
			</p>
			<%= link_to 'Contact Us', contact_us_path, :class=>"btn btn-primary pull-right left-padding"%> 
			<%= link_to 'Learn More', golden_rule_path, :class=>"btn btn-primary pull-right"%> 
		</div>
	</div>
</div>

app/views/pages/videos.html.erb
<h1>Pages#Videos</h1>
<p>Find me in app/views/pages/Videos.html.erb</p>